# Generated by Django 4.1.4 on 2023-07-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pic',
            new_name='picture',
        ),
    ]
