# Generated by Django 4.1.4 on 2023-07-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_profile_picture_posts_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='is_it_a_Image',
            new_name='is_it_an_Image',
        ),
    ]
