# Generated by Django 4.1.4 on 2023-07-13 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_posts_published_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
