# Generated by Django 4.1.4 on 2023-07-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_login_model_alter_posts_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
