# Generated by Django 4.1.4 on 2023-07-18 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_model',
        ),
    ]
